package com.example.export

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.ai.PrioritizedItem
import com.example.ai.TodayBriefing
import com.example.ai.UnifiedScholarContext
import java.io.File
import java.io.FileOutputStream

object BriefingExporter {

    /**
     * Formats Today's Briefing as a structured Markdown document.
     * Only contains real existing user records; never invents data.
     */
    fun formatMarkdown(briefing: TodayBriefing, context: UnifiedScholarContext): String {
        return buildString {
            appendLine("# CS Scholar OS — Today's Briefing")
            appendLine("**Date:** ${briefing.dateSummary}")
            val scholar = context.userProfile?.name ?: "International Scholar"
            val university = context.universityProfile?.university ?: "Yanshan University"
            appendLine("**Scholar:** $scholar • $university")
            appendLine()

            // 1. Overview
            appendLine("## Summary & Priorities")
            if (briefing.isEmptyState) {
                appendLine("- No urgent tasks or events scheduled for today.")
            } else if (briefing.prioritiesOverview.isNotEmpty()) {
                briefing.prioritiesOverview.forEach { item ->
                    appendLine("- $item")
                }
            } else {
                appendLine("- No urgent tasks or events scheduled for today.")
            }
            appendLine()

            // 2. High Priority
            if (briefing.highPriorityItems.isNotEmpty()) {
                appendLine("## High Priority (Immediate Action)")
                briefing.highPriorityItems.forEach { item ->
                    appendLine("- **${item.title}** (${item.urgencyReason})")
                    if (item.subtitle.isNotBlank()) {
                        appendLine("  *${item.subtitle}* [Module: ${item.moduleLabel}]")
                    }
                }
                appendLine()
            }

            // 3. Today's Classes
            if (context.todayClasses.isNotEmpty()) {
                appendLine("## Scheduled Classes")
                context.todayClasses.forEach { cls ->
                    appendLine("- **${cls.startTime} - ${cls.endTime}**: ${cls.courseCode} ${cls.courseName} @ ${cls.classroom} (Teacher: ${cls.teacher})")
                }
                appendLine()
            }

            // 4. Recommended
            if (briefing.recommendedItems.isNotEmpty()) {
                appendLine("## Recommended Actions")
                briefing.recommendedItems.forEach { item ->
                    appendLine("- **${item.title}**: ${item.urgencyReason} [Module: ${item.moduleLabel}]")
                }
                appendLine()
            }

            // 5. Optional / Upcoming
            if (briefing.optionalItems.isNotEmpty()) {
                appendLine("## Optional / Upcoming")
                briefing.optionalItems.take(4).forEach { item ->
                    appendLine("- ${item.title} (Due: ${item.dueDate})")
                }
                appendLine()
            }

            // 6. Recent Activity
            if (context.researchProjects.isNotEmpty() || context.knowledgeItems.isNotEmpty()) {
                appendLine("## Active Projects & Knowledge")
                context.activeResearchProjects.take(2).forEach { p ->
                    appendLine("- Research Project: **${p.title}** (${p.progressPercent}% completed, Target: ${p.targetVenue})")
                }
                context.knowledgeItems.take(2).forEach { k ->
                    appendLine("- Knowledge Base: *${k.title}* (${k.category})")
                }
                appendLine()
            }

            appendLine("---")
            appendLine("*Generated by CS Scholar OS Unified AI Command Center*")
        }
    }

    /**
     * Formats Today's Briefing as clean plain text.
     */
    fun formatPlainText(briefing: TodayBriefing, context: UnifiedScholarContext): String {
        return buildString {
            appendLine("CS SCHOLAR OS — TODAY'S BRIEFING")
            appendLine("Date: ${briefing.dateSummary}")
            val scholar = context.userProfile?.name ?: "International Scholar"
            val university = context.universityProfile?.university ?: "Yanshan University"
            appendLine("Scholar: $scholar ($university)")
            appendLine("----------------------------------------")

            appendLine("\n[SUMMARY]")
            if (briefing.isEmptyState) {
                appendLine("• No urgent priorities recorded for today.")
            } else if (briefing.prioritiesOverview.isNotEmpty()) {
                briefing.prioritiesOverview.forEach { item ->
                    appendLine("• $item")
                }
            } else {
                appendLine("• No urgent priorities recorded for today.")
            }

            if (briefing.highPriorityItems.isNotEmpty()) {
                appendLine("\n[HIGH PRIORITY]")
                briefing.highPriorityItems.forEach { item ->
                    appendLine("• ${item.title} -> ${item.urgencyReason} [${item.moduleLabel}]")
                }
            }

            if (context.todayClasses.isNotEmpty()) {
                appendLine("\n[SCHEDULED CLASSES]")
                context.todayClasses.forEach { cls ->
                    appendLine("• ${cls.startTime}-${cls.endTime}: ${cls.courseCode} ${cls.courseName} @ ${cls.classroom}")
                }
            }

            if (briefing.recommendedItems.isNotEmpty()) {
                appendLine("\n[RECOMMENDED ACTIONS]")
                briefing.recommendedItems.forEach { item ->
                    appendLine("• ${item.title} (${item.moduleLabel})")
                }
            }

            if (briefing.optionalItems.isNotEmpty()) {
                appendLine("\n[UPCOMING / OPTIONAL]")
                briefing.optionalItems.take(4).forEach { item ->
                    appendLine("• ${item.title} (Due: ${item.dueDate})")
                }
            }

            appendLine("----------------------------------------")
            appendLine("CS Scholar OS • AI Command Center")
        }
    }

    /**
     * Generates a clean, readable PDF document using native Android PdfDocument.
     * Uses zero external libraries and outputs directly to app cache.
     */
    fun createPdfDocument(
        context: Context,
        briefing: TodayBriefing,
        scholarContext: UnifiedScholarContext
    ): File? {
        return try {
            val pdfDoc = PdfDocument()
            val pageWidth = 595 // Standard A4 width (points)
            val pageHeight = 842 // Standard A4 height (points)
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
            val page = pdfDoc.startPage(pageInfo)
            val canvas = page.canvas

            val titlePaint = Paint().apply {
                color = Color.parseColor("#0F172A")
                textSize = 18f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val subtitlePaint = Paint().apply {
                color = Color.parseColor("#0284C7")
                textSize = 11f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val sectionHeaderPaint = Paint().apply {
                color = Color.parseColor("#1E293B")
                textSize = 13f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val bodyPaint = Paint().apply {
                color = Color.parseColor("#334155")
                textSize = 10f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                isAntiAlias = true
            }

            val urgentPaint = Paint().apply {
                color = Color.parseColor("#DC2626")
                textSize = 10f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val linePaint = Paint().apply {
                color = Color.parseColor("#E2E8F0")
                strokeWidth = 1f
            }

            var y = 45f
            val startX = 40f
            val contentWidth = pageWidth - 80f

            // Title
            canvas.drawText("CS SCHOLAR OS — TODAY'S BRIEFING", startX, y, titlePaint)
            y += 18f

            val scholar = scholarContext.userProfile?.name ?: "Alexei Chen"
            val univ = scholarContext.universityProfile?.university ?: "Yanshan University"
            canvas.drawText("${briefing.dateSummary} • Scholar: $scholar ($univ)", startX, y, subtitlePaint)
            y += 16f
            canvas.drawLine(startX, y, startX + contentWidth, y, linePaint)
            y += 24f

            // 1. Overview
            canvas.drawText("TODAY'S PRIORITIES OVERVIEW", startX, y, sectionHeaderPaint)
            y += 16f
            if (briefing.prioritiesOverview.isNotEmpty()) {
                briefing.prioritiesOverview.forEach { ov ->
                    canvas.drawText("• $ov", startX + 10f, y, bodyPaint)
                    y += 14f
                }
            } else {
                canvas.drawText("• No urgent priorities or lectures scheduled for today.", startX + 10f, y, bodyPaint)
                y += 14f
            }
            y += 12f

            // 2. High Priority Items
            if (briefing.highPriorityItems.isNotEmpty()) {
                canvas.drawText("HIGH PRIORITY (IMMEDIATE ACTION)", startX, y, sectionHeaderPaint)
                y += 16f
                briefing.highPriorityItems.forEach { item ->
                    val text = "• [${item.priorityLevel.label}] ${item.title} (${item.urgencyReason})"
                    canvas.drawText(text.take(85), startX + 10f, y, urgentPaint)
                    y += 14f
                }
                y += 12f
            }

            // 3. Scheduled Classes
            if (scholarContext.todayClasses.isNotEmpty()) {
                canvas.drawText("TODAY'S SCHEDULED LECTURES", startX, y, sectionHeaderPaint)
                y += 16f
                scholarContext.todayClasses.forEach { cls ->
                    val clsText = "• ${cls.startTime} - ${cls.endTime} | ${cls.courseCode} ${cls.courseName} @ ${cls.classroom}"
                    canvas.drawText(clsText.take(85), startX + 10f, y, bodyPaint)
                    y += 14f
                }
                y += 12f
            }

            // 4. Recommended Actions
            if (briefing.recommendedItems.isNotEmpty()) {
                canvas.drawText("RECOMMENDED ACTIONS", startX, y, sectionHeaderPaint)
                y += 16f
                briefing.recommendedItems.forEach { item ->
                    val recText = "• ${item.title} -> ${item.urgencyReason} [${item.moduleLabel}]"
                    canvas.drawText(recText.take(85), startX + 10f, y, bodyPaint)
                    y += 14f
                }
                y += 12f
            }

            // 5. Active Projects & Knowledge
            if (scholarContext.activeResearchProjects.isNotEmpty()) {
                canvas.drawText("ACTIVE RESEARCH & SCHOLAR ROADMAP", startX, y, sectionHeaderPaint)
                y += 16f
                scholarContext.activeResearchProjects.take(2).forEach { p ->
                    val projText = "• Project: ${p.title} (${p.progressPercent}% progress, Target: ${p.targetVenue})"
                    canvas.drawText(projText.take(85), startX + 10f, y, bodyPaint)
                    y += 14f
                }
                y += 12f
            }

            // Footer
            y = pageHeight - 35f
            canvas.drawLine(startX, y, startX + contentWidth, y, linePaint)
            y += 16f
            val footerPaint = Paint().apply {
                color = Color.parseColor("#94A3B8")
                textSize = 9f
                isAntiAlias = true
            }
            canvas.drawText("CS Scholar OS • AI Command Center Daily Export • Non-fabricated data", startX, y, footerPaint)

            pdfDoc.finishPage(page)

            // Save to cache directory
            val cacheFile = File(context.cacheDir, "cs_scholar_briefing.pdf")
            val outputStream = FileOutputStream(cacheFile)
            pdfDoc.writeTo(outputStream)
            outputStream.flush()
            outputStream.close()
            pdfDoc.close()

            cacheFile
        } catch (_: Exception) {
            null
        }
    }

    /**
     * Standard Android share sheet using Intent.ACTION_SEND for text/markdown.
     */
    fun shareText(context: Context, text: String, title: String = "CS Scholar OS Daily Briefing") {
        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, title)
            putExtra(Intent.EXTRA_TEXT, text)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        val chooser = Intent.createChooser(sendIntent, "Share Daily Briefing via")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    /**
     * Standard Android share sheet for PDF file using FileProvider.
     */
    fun sharePdf(context: Context, pdfFile: File, title: String = "CS Scholar OS Daily Briefing PDF") {
        try {
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )

            val sendIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_SUBJECT, title)
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            val chooser = Intent.createChooser(sendIntent, "Export Briefing PDF via")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            // Fallback to text share if FileProvider fails
            shareText(context, "Briefing PDF export completed: ${pdfFile.name}")
        }
    }
}
